#!/usr/bin/env ruby
# Restart a Minecraft server.
# Usage: restart [server-name] [--warn] [--bukkit]

$:.unshift File.dirname(__FILE__)
load "env"

if ARGV.include?("-h") || ARGV.include?("--help")
  STDERR.puts "Usage: restart [server-name] [--warn]"
  exit 1
end

$server_name = ARGV.find { |arg| arg =~ /^\w+$/ } || "survival"

if server_running?
  if ARGV.include?("--warn")
    send_command "say Server restarting in one minute!"
    sleep 60
  end

  send_command "stop"

  puts "Waiting for server to shut down..."
  sleep(3) until !server_running?
  puts "Server stopped."
end

command = [bin_path.join("daemon")]
command << $server_name
command << "--bukkit" if ARGV.include?("--bukkit")
command = command.join(" ")

puts command
exec command
