#!/usr/bin/env ruby
# Restart a Minecraft server.
# Usage: restart [server-name] [--warn] [daemon options]

$:.unshift File.dirname(__FILE__)
load "env"

if ARGV.delete("-h") || ARGV.delete("--help")
  STDERR.puts "Usage: restart [server-name] [--warn] [daemon options]"
  exit 1
end

$server_name = ARGV.find { |arg| arg =~ /^\S+$/ } || "survival"

if server_running?
  if ARGV.delete("--warn")
    send_command "say Server restarting in one minute!"
    sleep 60
  end

  send_command "stop"

  puts "Waiting for server to shut down..."
  sleep(3) until !server_running?
  puts "Server stopped."
end

command = [bin_path.join("daemon"), *ARGV].join(" ")

puts command
exec command
