#!/usr/bin/env ruby
# Start a Minecraft server.
# Usage: start [server-name]

require "pathname"
require "shellwords"

root = Pathname.new(File.expand_path(File.join(File.dirname(__FILE__), "..")))
server_name = ARGV.find { |arg| arg =~ /^\S+$/ } || "survival"
server = root.join("servers", server_name)

unless server.directory?
  STDERR.puts "Error: #{server} does not exist!"
  exit 1
end

Dir.chdir(server.to_s)

command = [`which nice`.chomp]
command << "-n 1"
command << `which java`.chomp
command << "-Xincgc"
command << "-Xms2G"
command << "-Xmx3G"
command << "-jar"
command << root.join("lib/minecraft_server.jar")
command << "nogui"

$server_name = server_name.dup
$command = command.join(" ")

if $0 == __FILE__
  puts $command
  exec $command
end
